# Generated by Django 2.1.5 on 2019-01-27 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 18, 31, 29, 191034)),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 18, 31, 29, 188942)),
        ),
    ]
